exports.emailMode = {
  NORMAL: 'NORMAL',
  ORDER: 'ORDER',
  ORDERITEM: 'ORDERITEM',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  VEHICLE_REQUEST: 'VEHICLE_REQUEST',
};
